In [33]:
import numpy as np

a1 = np.array([1,2,3,4])     #1-D Array
a2 = np.array([[1,2], [3,4]])        #2-D Array
a3 = np.array([[[1,2], [3,4]], [[5,6],[7,8]]])     #3-D Array

a4 = np.zeros((3, 2))   #create a zero array
a5 = np.ones((3,2))     #Create a ones array
a6 = np.eye(3)          #create an identity matrix - each row has one 1 and all other values are zero


a7 = np.full((2,3), 4)       #create a 2-D array with 3 columns value as 4
arr4 = np.random.randint(1, 11, size=(2, 5))     #create an 2*5 array with numbers from 1-10

#arange focuses on the step size between values, while linspace focuses on the number of values within a range.
a9 = np.arange(0, 10, 3)   # [0, 2, 4, 6, 8]
a10 = np.linspace(0, 20, 5)  # 5 evenly spaced values from 0 to 20 - 0 and 20 are inclusive 

print(a1)
print(a2)
print(a3)
print(a4)
print(a5)
print(a6)
print(a7)
print(a8)
print(a9)
print(a10)

"""
a.shape       # Dimensions (rows, columns)
a.size        # Total number of elements
a.ndim        # Number of axes (dimensions)
a.dtype       # Data type (e.g., int32, float64)
"""

a = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape:", a.shape)
print("Size:", a.size)
print("Dimensions:", a.ndim)
print("Data type:", a.dtype)

[1 2 3 4]
[[1 2]
 [3 4]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[4 4 4]
 [4 4 4]]
[0 3 6 9]
[0 3 6 9]
[ 0.  5. 10. 15. 20.]
Shape: (2, 3)
Size: 6
Dimensions: 2
Data type: int64


In [14]:
import numpy as np

a = np.array([10, 20, 30])
a[0]    # 10 (1st element)
a[2]    # 30 (3rd element)

b = np.array([[10, 20], [30, 40]])
b[0, 0]  # 10 (row 0, col 0)
b[1, 1]  # 40 (row 1, col 1)

a = np.array([10, 20, 30, 40, 50])
a[1:4]      # [20, 30, 40]
a[::-1]     # Reverses the array → [50, 40, 30, 20, 10]

arr = np.array([[1, 2, 3], [4, 5, 6]])
arr[0, :]     # First row → [1, 2, 3]
arr[:, 1]     # Second column → [2, 5]

a = np.array([10, 20, 30, 40])
a[[0, 2]]     # Select multiple elements → [10, 30]

#arr[row_start:row_end, column_start:column_end]

#Sample Array
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

# Exercise 1: Access a Specific Element
print(arr[1,2])

#Exercise 2: Slice a Subarray - Extract the top-left 2x2 part
#arr[row_start:row_end, column_start:column_end]
print(arr[0:2, 0:2])

#Exercise 3: Get a Row and a Column - Print the 2nd row, Print the 3rd column
print(arr[1,:])
print(arr[:,2])

#Exercise 4: Reverse a 1D Array
a = np.array([1, 2, 3, 4, 5])
reversed_a = a[::-1]
print(reversed_a)

#Exercise 5: Filter Elements > 50
filtered = arr[arr > 50]
print(filtered)

#Exercise 6: Filter Elements > 50 and replace with 999
arr[arr > 50] = 999
print(arr)

60
[[10 20]
 [40 50]]
[40 50 60]
[30 60 90]
[5 4 3 2 1]
[60 70 80 90]
[[ 10  20  30]
 [ 40  50 999]
 [999 999 999]]


In [6]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)       # [5, 7, 9]
print(a * b)       # [4, 10, 18]
print(a - b)       # [-3, -3, -3]
print(a / b)       # [0.25, 0.4, 0.5]

print(a ** 2)      # [1, 4, 9]
print(a + 10)     # [11, 12, 13]
print(a * 2)      # [2, 4, 6]


#2-D array

c = np.array([[1, 2], [3, 4]])
d = np.array([[5, 6], [7, 8]])

np.dot(c, d)     # Matrix multiplication
print(c @ d)     # Same as np.dot(a, b)
print(c.T)              # Transpose



#Braodcasting

e = np.array([[1], [2], [3]])     # Shape (3, 1)
f = np.array([10, 20, 30])        # Shape (3,)

result = e + f
print(result)


a1 = np.array([1, 2, 3])
b1 = np.array([4, 5, 6])

m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])

#Exercise 1: Element-wise Addition - a1 +b1
print(a1+b1)

#Exercise 2: Scalar Multiplication - Multiply all elements in a1 by 10.
print(a1 * 10)

#Exercise 3: Matrix Multiplication - Perform matrix multiplication between m1 and m2.
print(m1 @ m2)

#Exercise 4: Transpose a Matrix - Transpose m1
print(m1.T)

#Exercise 5: Use Broadcasting - Add a column vector and a row vector:
col = np.array([[1], [2], [3]])       # shape (3, 1)
row = np.array([10, 20, 30])          # shape (3,)
broadcasted_sum = col + row
print(broadcasted_sum)

[5 7 9]
[ 4 10 18]
[-3 -3 -3]
[0.25 0.4  0.5 ]
[1 4 9]
[11 12 13]
[2 4 6]
[[19 22]
 [43 50]]
[[1 3]
 [2 4]]
[[11 21 31]
 [12 22 32]
 [13 23 33]]
[5 7 9]
[10 20 30]
[[19 22]
 [43 50]]
[[1 3]
 [2 4]]
[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [15]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.sum())
print(arr.mean())
print(arr.min())
print(arr.max())
print(arr.std())
print(arr.var())

print(arr.sum(axis=0))  #colunm - wise
print(arr.sum(axis=1))  #row - wise

print(np.median(arr))                  # Median of array
print(np.percentile(arr, 75))          # 75th percentile
print(np.sort(arr, axis=1) )           # Sort each 

print(np.unique(arr))                # Unique values
print(np.unique(arr, return_counts=True)) # Values and their frequencies



#Sample
arr1 = np.array([
    [4, 8, 6],
    [10, 12, 14],
    [1, 3, 5]
])

#Exercise 1: Sum all elements in the array
print(arr1.sum())

#Exercise 2: Compute row-wise and column-wise averages
row_avg = arr1.mean(axis=1)      # Mean of each row
col_avg = arr1.mean(axis=0)      # Mean of each column
print("Row-wise:", row_avg)
print("Column-wise:", col_avg)



21
3.5
1
6
1.707825127659933
2.9166666666666665
[5 7 9]
[ 6 15]
3.5
4.75
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
(array([1, 2, 3, 4, 5, 6]), array([1, 1, 1, 1, 1, 1]))
63


In [35]:
a = np.array([1, 2, 3, 4, 5, 6])
b = a.reshape(2, 3)
print(b)

print(a.flatten())   # Returns a copy (new array)
print(a.ravel())     # Returns a view (same memory if possible)

print(b.T)

a = np.array([1, 2])
b = np.array([3, 4])
print("vertical stack: ",np.vstack([a, b]))
print("horizontal stack: ", np.hstack([a, b]))

np.concatenate([a, b])         # 1D arrays

a = np.array([1, 2, 3, 4, 5, 6])
b = np.split(a, 3)
print(b)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]
vertical stack:  [[1 2]
 [3 4]]
horizontal stack:  [1 2 3 4]
[array([1, 2]), array([3, 4]), array([5, 6])]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[10 30]
 [20 40]]


In [39]:
import numpy as np

#Uniform Distribution (between 0 and 1)
print(np.random.rand(3))        # 1D array with 3 values
print(np.random.rand(2, 3))     # 2x3 array

#Standard Normal Distribution (mean=0, std=1)
print(np.random.randn(2, 2))    # 2x2 array from standard normal

#Random Integers
print(np.random.randint(1, 10, size=(2, 4)))  # Integers from 1 to 9 in 2x4 shape

[0.35350728 0.76431501 0.5973626 ]
[[0.84991741 0.1202171  0.33452498]
 [0.36034063 0.17443036 0.94862796]]
[[ 1.31296638  0.34614907]
 [-0.87642167  1.26131427]]
[[9 1 2 2]
 [8 7 7 4]]
