Load the Data

In [1]:
import numpy as np
import os

# Define the file path
file_path = "/Users/snehakalidindi/Documents/NYU-Data-Science-Bootcamp-Spring-2025/Datasets/iris.data"

# Check if the file exists before loading
if os.path.exists(file_path):
    print("File found! Loading dataset...")
    iris_2d = np.genfromtxt(file_path, delimiter=',', dtype='float', usecols=[0,1,2,3])
    print("First 5 rows:\n", iris_2d[:5])
else:
    print("Error: File not found! Check the path and try again.")

File found! Loading dataset...
First 5 rows:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


Numpy 

Question 1: Stack Two NumPy Arrays Vertically and Horizontally

In [2]:
# Define two custom NumPy arrays using the first 5 rows of iris_2d
A = iris_2d[:5]  # First 5 rows
B = iris_2d[5:10]  # Next 5 rows

# Stack vertically
vertical_stack = np.vstack((A, B))

# Stack horizontally
horizontal_stack = np.hstack((A, B))

print("Vertical Stack:\n", vertical_stack)
print("\nHorizontal Stack:\n", horizontal_stack)

Vertical Stack:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]

Horizontal Stack:
 [[5.1 3.5 1.4 0.2 5.4 3.9 1.7 0.4]
 [4.9 3.  1.4 0.2 4.6 3.4 1.4 0.3]
 [4.7 3.2 1.3 0.2 5.  3.4 1.5 0.2]
 [4.6 3.1 1.5 0.2 4.4 2.9 1.4 0.2]
 [5.  3.6 1.4 0.2 4.9 3.1 1.5 0.1]]


Question 2: Find Common Elements Between A and B

In [3]:
# Find intersection (common elements) between A and B
common_elements = np.intersect1d(A, B)

print("Common Elements:\n", common_elements)

Common Elements:
 [0.2 1.4 1.5 3.1 4.6 4.9 5. ]


Question 3: Extract Numbers Between 5 and 10

In [4]:
# Extract numbers between 5 and 10 from the first 10 rows of iris_2d
filtered_numbers = iris_2d[:10][(iris_2d[:10] >= 5) & (iris_2d[:10] <= 10)]

print("Numbers between 5 and 10:\n", filtered_numbers)

Numbers between 5 and 10:
 [5.1 5.  5.4 5. ]


Question 4: Filter Rows in the Iris Dataset

In [5]:
# Filter rows where petal length (3rd column) > 1.5 and sepal length (1st column) < 5.0
filtered_rows = iris_2d[(iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)]

print("Filtered rows:\n", filtered_rows)

Filtered rows:
 [[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


Question 1: Filter ‘Manufacturer’, ‘Model’, and ‘Type’ for Every 20th Row

In [7]:
import pandas as pd
import numpy as np

# Load dataset
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Select every 20th row starting from index 0
filtered_df = df.iloc[::20, :][['Manufacturer', 'Model', 'Type']]

# Display the filtered data
print(filtered_df)

   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


Question 2: Replace Missing Values in Min.Price and Max.Price Columns

In [ ]:
# Load dataset
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Replace missing values with column means
df['Min.Price'].fillna(df['Min.Price'].mean(), inplace=True)
df['Max.Price'].fillna(df['Max.Price'].mean(), inplace=True)

# Display first few rows to verify changes
print(df[['Min.Price', 'Max.Price']].head())

Question 3: Get Rows Where Row Sum > 100

In [8]:
# Create a DataFrame with random integers
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

# Find rows where the sum is greater than 100
filtered_rows = df[df.sum(axis=1) > 100]

# Display the filtered rows
print(filtered_rows)

     0   1   2   3
3   33  12  34  33
5   32  31  24  33
7   19  39  33  19
9   23  30  36  23
11  27  35  18  39
12  14  31  29  37
13  18  22  31  35
14  36  25  18  31
